# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 33fdf0e9f8a73e84844a1475c0f46ba98ca762aac81d2170e3c03450a02cf6fbc887a0c578e2f592f522e78bfd5e16c5b522f6cbaa3ebd69e4a237954e076116

test:
  secret_key_base: 43807a1792a41b3ccf88a44671c2db9997ba846ff495ecd13c09b7f4ae6f066f6a8726bfe4b79dc1751ec98704cc7df8aad182f8859ecca6e214d1cd36d15747

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
